title:              Mikael
email:              contato.mikaeldsm@gmail.com
description:        Seja curioso. Leia de tudo. Tente coisas novas. O que as pessoas chamam de inteligência se resume a curiosidade — Aaron Swartz
author:             Mikael
baseurl:            ""
url:                "akamdsm.github.io"

# Social Profiles
twitter_username: akamdsm
github_username: akamdsm  
linkedin_username: mikael-matos

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
